2022-01-06 00:02:18,579 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-01-06 00:02:18,579 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\SSY\AppData\Local\Programs\Python\Python37-32\lib\site-packages\instabot\bot\bot.py
2022-01-06 00:02:18,580 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-01-06 00:02:18,826 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [429]>
2022-01-06 00:02:18,826 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-01-06 00:02:18,826 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-01-06 00:02:18,826 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
